modLoader="javafml"
loaderVersion="[34,)"
license="GPL3"
issueTrackerURL="https://github.com/MrCrayfish/Configured/issues"

[[mods]]
modId="configured"
version="1.4.0"
displayName="Configured"
credits="Hatsondogs for creating icons. LizterZapZap for creating mod logo"
authors="MrCrayfish"
description="Creates a simple GUI config for every mod!"
logoFile="configured_logo.png"
logoBlur=false
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=configured"
displayURL="https://mrcrayfish.com/mods?id=configured"

[[dependencies.configured]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.configured]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.configured]]
    modId="catalogue"
    mandatory=false
    versionRange="[1.2.0,)"
    ordering="NONE"
    side="CLIENT"

[modproperties.configured]
    catalogueImageIcon="configured_icon.png"
    configuredBackground="minecraft:textures/block/stone.png"
